sudo: required
language: php
dist: trusty

php:
  - 7.2

install:
  - travis_retry composer install --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp .env.testing .env
  - php artisan dusk:chrome-driver 73
  - php artisan serve &

script:
  - php artisan dusk
  - php vendor/phpunit/phpunit/phpunit
