sudo: required
language: php
dist: trusty

php:
  - 7.3

addons:
  chrome: stable

install:
  - mysql -e 'create database lingogame_test;'
  - cp .env.testing .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate --force
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php vendor/phpunit/phpunit/phpunit
#  - php artisan dusk
