sudo: required
language: php
dist: trusty

php:
  - 7.3

addons:
  chrome: stable

install:
  - cp .env.testing .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan dusk:chrome-driver 72
  - php artisan serve &

script:
  - php vendor/phpunit/phpunit/phpunit
  - php artisan dusk
